// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    category, description, amount, date, user_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, category, description, amount, date, user_id, created_at
`

type CreateExpenseParams struct {
	Category    string         `db:"category" json:"category"`
	Description sql.NullString `db:"description" json:"description"`
	Amount      string         `db:"amount" json:"amount"`
	Date        time.Time      `db:"date" json:"date"`
	UserID      uuid.NullUUID  `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.Date,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Date,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT id, category, description, amount, date, user_id, created_at
FROM expenses
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetExpense(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Date,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, category, description, amount, date, user_id, created_at
FROM expenses
WHERE ($1 = '0001-01-01'::date OR date >= $1)
  AND ($2 = '0001-01-01'::date OR date <= $2)
  AND ($3 = '' OR category = $3)
ORDER BY date DESC, created_at DESC
LIMIT $4 OFFSET $5
`

type ListExpensesParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	Column3 interface{} `db:"column_3" json:"column_3"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpenses,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Description,
			&i.Amount,
			&i.Date,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET category = $2, description = $3, amount = $4, date = $5
WHERE id = $1
RETURNING id, category, description, amount, date, user_id, created_at
`

type UpdateExpenseParams struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Category    string         `db:"category" json:"category"`
	Description sql.NullString `db:"description" json:"description"`
	Amount      string         `db:"amount" json:"amount"`
	Date        time.Time      `db:"date" json:"date"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.ID,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.Date,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Date,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
