// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu_items.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (
    name, category_id, description, price, cost
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, category_id, description, price, cost, is_available, created_at, updated_at
`

type CreateMenuItemParams struct {
	Name        string         `db:"name" json:"name"`
	CategoryID  uuid.UUID      `db:"category_id" json:"category_id"`
	Description sql.NullString `db:"description" json:"description"`
	Price       string         `db:"price" json:"price"`
	Cost        string         `db:"cost" json:"cost"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, createMenuItem,
		arg.Name,
		arg.CategoryID,
		arg.Description,
		arg.Price,
		arg.Cost,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
UPDATE menu_items
SET is_available = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMenuItem, id)
	return err
}

const getMenuItem = `-- name: GetMenuItem :one
SELECT id, name, category_id, description, price, cost, is_available, created_at, updated_at
FROM menu_items
WHERE id = $1 AND is_available = true
LIMIT 1
`

func (q *Queries) GetMenuItem(ctx context.Context, id uuid.UUID) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, getMenuItem, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, name, category_id, description, price, cost, is_available, created_at, updated_at
FROM menu_items
WHERE is_available = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListMenuItemsParams struct {
	IsAvailable bool  `db:"is_available" json:"is_available"`
	Limit       int32 `db:"limit" json:"limit"`
	Offset      int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListMenuItems(ctx context.Context, arg ListMenuItemsParams) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItems, arg.IsAvailable, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Description,
			&i.Price,
			&i.Cost,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByCategory = `-- name: ListMenuItemsByCategory :many
SELECT id, name, category_id, description, price, cost, is_available, created_at, updated_at
FROM menu_items
WHERE category_id = $1 AND is_available = true
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListMenuItemsByCategoryParams struct {
	CategoryID uuid.UUID `db:"category_id" json:"category_id"`
	Limit      int32     `db:"limit" json:"limit"`
	Offset     int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListMenuItemsByCategory(ctx context.Context, arg ListMenuItemsByCategoryParams) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItemsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Description,
			&i.Price,
			&i.Cost,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET name = $2, category_id = $3, description = $4, price = $5, cost = $6, is_available = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, name, category_id, description, price, cost, is_available, created_at, updated_at
`

type UpdateMenuItemParams struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	CategoryID  uuid.UUID      `db:"category_id" json:"category_id"`
	Description sql.NullString `db:"description" json:"description"`
	Price       string         `db:"price" json:"price"`
	Cost        string         `db:"cost" json:"cost"`
	IsAvailable bool           `db:"is_available" json:"is_available"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Description,
		arg.Price,
		arg.Cost,
		arg.IsAvailable,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
