// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_number, user_id, total_amount, discount_amount, tax_amount
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, order_number, user_id, status, total_amount, discount_amount, tax_amount, 
          payment_method, payment_status, completed_at, created_at, updated_at
`

type CreateOrderParams struct {
	OrderNumber    string    `db:"order_number" json:"order_number"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	TotalAmount    string    `db:"total_amount" json:"total_amount"`
	DiscountAmount string    `db:"discount_amount" json:"discount_amount"`
	TaxAmount      string    `db:"tax_amount" json:"tax_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.OrderNumber,
		arg.UserID,
		arg.TotalAmount,
		arg.DiscountAmount,
		arg.TaxAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, order_number, user_id, status, total_amount, discount_amount, tax_amount, 
       payment_method, payment_status, completed_at, created_at, updated_at
FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, order_number, user_id, status, total_amount, discount_amount, tax_amount, 
       payment_method, payment_status, completed_at, created_at, updated_at
FROM orders
WHERE order_number = $1
LIMIT 1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, order_number, user_id, status, total_amount, discount_amount, tax_amount, 
       payment_method, payment_status, completed_at, created_at, updated_at
FROM orders
WHERE ($1 = '' OR status = $1) 
  AND ($2 = '00000000-0000-0000-0000-000000000000'::uuid OR user_id = $2)
  AND ($3 = '0001-01-01'::date OR created_at >= $3) 
  AND ($4 = '0001-01-01'::date OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListOrdersParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	Column3 interface{} `db:"column_3" json:"column_3"`
	Column4 interface{} `db:"column_4" json:"column_4"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPayment = `-- name: UpdateOrderPayment :exec
UPDATE orders
SET payment_method = $2, payment_status = $3, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateOrderPaymentParams struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	PaymentMethod sql.NullString `db:"payment_method" json:"payment_method"`
	PaymentStatus string         `db:"payment_status" json:"payment_status"`
}

func (q *Queries) UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderPayment, arg.ID, arg.PaymentMethod, arg.PaymentStatus)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const updateOrderTotal = `-- name: UpdateOrderTotal :exec
UPDATE orders
SET total_amount = $2, discount_amount = $3, tax_amount = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderTotalParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	TotalAmount    string    `db:"total_amount" json:"total_amount"`
	DiscountAmount string    `db:"discount_amount" json:"discount_amount"`
	TaxAmount      string    `db:"tax_amount" json:"tax_amount"`
}

func (q *Queries) UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderTotal,
		arg.ID,
		arg.TotalAmount,
		arg.DiscountAmount,
		arg.TaxAmount,
	)
	return err
}
