// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, menu_item_id, quantity, unit_price, total_price
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, order_id, menu_item_id, quantity, unit_price, total_price, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID    uuid.UUID `db:"order_id" json:"order_id"`
	MenuItemID uuid.UUID `db:"menu_item_id" json:"menu_item_id"`
	Quantity   int32     `db:"quantity" json:"quantity"`
	UnitPrice  string    `db:"unit_price" json:"unit_price"`
	TotalPrice string    `db:"total_price" json:"total_price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items
WHERE id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItem, id)
	return err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT id, order_id, menu_item_id, quantity, unit_price, total_price, created_at, updated_at
FROM order_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderItem(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItem, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, menu_item_id, quantity, unit_price, total_price, created_at, updated_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsWithDetails = `-- name: GetOrderItemsWithDetails :many
SELECT oi.id, oi.order_id, oi.menu_item_id, mi.name as menu_item_name, oi.quantity, oi.unit_price, oi.total_price, oi.created_at, oi.updated_at
FROM order_items oi
JOIN menu_items mi ON oi.menu_item_id = mi.id
WHERE oi.order_id = $1
ORDER BY oi.created_at
`

type GetOrderItemsWithDetailsRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	OrderID      uuid.UUID `db:"order_id" json:"order_id"`
	MenuItemID   uuid.UUID `db:"menu_item_id" json:"menu_item_id"`
	MenuItemName string    `db:"menu_item_name" json:"menu_item_name"`
	Quantity     int32     `db:"quantity" json:"quantity"`
	UnitPrice    string    `db:"unit_price" json:"unit_price"`
	TotalPrice   string    `db:"total_price" json:"total_price"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetOrderItemsWithDetails(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsWithDetails, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsWithDetailsRow
	for rows.Next() {
		var i GetOrderItemsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.MenuItemName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE order_items
SET quantity = $2, unit_price = $3, total_price = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, menu_item_id, quantity, unit_price, total_price, created_at, updated_at
`

type UpdateOrderItemParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Quantity   int32     `db:"quantity" json:"quantity"`
	UnitPrice  string    `db:"unit_price" json:"unit_price"`
	TotalPrice string    `db:"total_price" json:"total_price"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, updateOrderItem,
		arg.ID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
