// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateInventoryRecord(ctx context.Context, menuItemID uuid.UUID) error
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteMenuItem(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetInventoryByMenuItem(ctx context.Context, menuItemID uuid.UUID) (Inventory, error)
	GetMenuItem(ctx context.Context, id uuid.UUID) (MenuItem, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListInventory(ctx context.Context, arg ListInventoryParams) ([]ListInventoryRow, error)
	ListMenuItems(ctx context.Context, arg ListMenuItemsParams) ([]MenuItem, error)
	ListMenuItemsByCategory(ctx context.Context, arg ListMenuItemsByCategoryParams) ([]MenuItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInventoryStock(ctx context.Context, arg UpdateInventoryStockParams) error
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
