// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_transactions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createStockTransaction = `-- name: CreateStockTransaction :one
INSERT INTO stock_transactions (
    menu_item_id, transaction_type, quantity, previous_stock, current_stock,
    reason, reference_type, reference_id, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, menu_item_id, transaction_type, quantity, previous_stock, current_stock,
          reason, reference_type, reference_id, user_id, created_at
`

type CreateStockTransactionParams struct {
	MenuItemID      uuid.UUID      `db:"menu_item_id" json:"menu_item_id"`
	TransactionType string         `db:"transaction_type" json:"transaction_type"`
	Quantity        int32          `db:"quantity" json:"quantity"`
	PreviousStock   int32          `db:"previous_stock" json:"previous_stock"`
	CurrentStock    int32          `db:"current_stock" json:"current_stock"`
	Reason          string         `db:"reason" json:"reason"`
	ReferenceType   sql.NullString `db:"reference_type" json:"reference_type"`
	ReferenceID     uuid.NullUUID  `db:"reference_id" json:"reference_id"`
	UserID          uuid.NullUUID  `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateStockTransaction(ctx context.Context, arg CreateStockTransactionParams) (StockTransaction, error) {
	row := q.db.QueryRowContext(ctx, createStockTransaction,
		arg.MenuItemID,
		arg.TransactionType,
		arg.Quantity,
		arg.PreviousStock,
		arg.CurrentStock,
		arg.Reason,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.UserID,
	)
	var i StockTransaction
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.TransactionType,
		&i.Quantity,
		&i.PreviousStock,
		&i.CurrentStock,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listStockTransactions = `-- name: ListStockTransactions :many
SELECT st.id, st.menu_item_id, mi.name as menu_item_name, st.transaction_type,
       st.quantity, st.previous_stock, st.current_stock, st.reason,
       st.reference_type, st.reference_id, st.user_id, u.username as user_name, st.created_at
FROM stock_transactions st
LEFT JOIN menu_items mi ON st.menu_item_id = mi.id
LEFT JOIN users u ON st.user_id = u.id
WHERE ($1::uuid IS NULL OR st.menu_item_id = $1)
  AND ($2::date IS NULL OR st.created_at >= $2)
  AND ($3::date IS NULL OR st.created_at <= $3)
ORDER BY st.created_at DESC
LIMIT $4 OFFSET $5
`

type ListStockTransactionsParams struct {
	Column1 uuid.UUID `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
	Column3 time.Time `db:"column_3" json:"column_3"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

type ListStockTransactionsRow struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	MenuItemID      uuid.UUID      `db:"menu_item_id" json:"menu_item_id"`
	MenuItemName    sql.NullString `db:"menu_item_name" json:"menu_item_name"`
	TransactionType string         `db:"transaction_type" json:"transaction_type"`
	Quantity        int32          `db:"quantity" json:"quantity"`
	PreviousStock   int32          `db:"previous_stock" json:"previous_stock"`
	CurrentStock    int32          `db:"current_stock" json:"current_stock"`
	Reason          string         `db:"reason" json:"reason"`
	ReferenceType   sql.NullString `db:"reference_type" json:"reference_type"`
	ReferenceID     uuid.NullUUID  `db:"reference_id" json:"reference_id"`
	UserID          uuid.NullUUID  `db:"user_id" json:"user_id"`
	UserName        sql.NullString `db:"user_name" json:"user_name"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) ListStockTransactions(ctx context.Context, arg ListStockTransactionsParams) ([]ListStockTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStockTransactions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockTransactionsRow
	for rows.Next() {
		var i ListStockTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.MenuItemName,
			&i.TransactionType,
			&i.Quantity,
			&i.PreviousStock,
			&i.CurrentStock,
			&i.Reason,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.UserID,
			&i.UserName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
